%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/sailingpc/MATLAB/Quadcopter_Variable_Pitch/quat_controller_main_working/xf-naca0010-il-100000.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/12 08:38:46

%% Initialize variables.
filename = '/home/sailingpc/MATLAB/Quadcopter_Variable_Pitch/quat_controller_main_working/xf-naca0010-il-100000.csv';
delimiter = ',';
startRow = 12;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
blade.Alpha = dataArray{:, 1};
blade.Cl = dataArray{:, 2};
blade.Cd = dataArray{:, 3};
blade.Cdp = dataArray{:, 4};
blade.Cm = dataArray{:, 5};
blade.Top_Xtr = dataArray{:, 6};
blade.vBot_Xtr = dataArray{:, 7};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;